# Generated by Django 3.1.4 on 2021-05-22 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travellingApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('country', models.CharField(default='Pakistan', max_length=30)),
                ('picture', models.ImageField(upload_to='uploads/')),
                ('city', models.CharField(default='Karachi', max_length=100)),
                ('trending', models.BooleanField(default=False)),
                ('price', models.IntegerField(default=15000)),
                ('discount', models.IntegerField(default=0)),
                ('package', models.CharField(default='1 day/night', max_length=20)),
            ],
        ),
    ]
