# Generated by Django 3.1.4 on 2021-05-24 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travellingApp', '0005_auto_20210524_1314'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('location', models.CharField(default='Karachi', max_length=100)),
            ],
        ),
    ]
