# Generated by Django 3.1.4 on 2021-05-24 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travellingApp', '0006_hotel'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='picture',
            field=models.ImageField(default='uploads/hotels/IslamabadHotel.jpg', upload_to='uploads/hotels/'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='picture',
            field=models.ImageField(default='uploads/places/dubai.png', upload_to='uploads/places/'),
        ),
    ]
