# Generated by Django 3.1.4 on 2021-05-24 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travellingApp', '0007_auto_20210524_1341'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locFrom', models.CharField(default='Dubai', max_length=30)),
                ('locTo', models.CharField(default='Karachi', max_length=30)),
                ('price', models.IntegerField(default=100)),
                ('country', models.CharField(default='Pakistan', max_length=30)),
                ('date', models.DateField()),
            ],
        ),
    ]
