# Generated by Django 3.1.4 on 2021-05-24 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travellingApp', '0008_flight'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Availability',
        ),
    ]
