# Generated by Django 3.1.4 on 2021-05-24 10:08

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('travellingApp', '0009_delete_availability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
        migrations.AlterField(
            model_name='flight',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
