# Generated by Django 3.1.4 on 2021-05-25 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travellingApp', '0010_auto_20210524_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='Email',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='contact',
            name='Message',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='contact',
            name='Name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='contact',
            name='Subject',
            field=models.CharField(default='', max_length=100),
        ),
    ]
